name: gym_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sa_multi_tween: ^1.1.1
#  page_transition: ^1.1.5
  simple_animations: ^2.2.1
#  titled_navigation_bar: ^3.5.0
#  table_calendar: ^2.2.1
  http: ^0.12.0+2
#  flutter_webview_plugin: ^0.3.10
#  requests: ^3.0.3
#  shared_preferences: ^0.5.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/loginBackground.jpg
    - images/backgroundGymapp.jpg
    - images/signupbackground.jpg
    - images/profile.png

  fonts:
    - family: Calistoga
      fonts:
        - asset: fonts/Calistoga.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster.ttf


